# Site settings
title: Jesse Shawl
email: jesse@jshawl.com
username: jshawl
description: "Jesse Shawl makes websites."

# Build settings
markdown: kramdown
permalink: /:title/

sass:
    sass_dir: scss

collections:
  teaches:
    output: true
  is-all-about:
    output: true
  makes-things:
    output: true

navigation:
  - title: Blog
    url: /index.html
  - title: About
    url: /is-all-about/index.html
  - title: Projects
    url: /makes-things/index.html
  - title: Teaching
    url: /teaches/index.html
