# Site settings
title: Jesse Shawl
email: jesse@jshawl.com
username: jshawl
description: "Jesse Shawl makes websites."
baseurl: ""
url: "http://jesse.sh/"

# Build settings
markdown: kramdown
permalink: /:title/
