# Site settings
title: Jesse Shawl
email: jesse@jshawl.com
username: jshawl
description: "Jesse Shawl makes websites."

# Build settings
markdown: kramdown
permalink: /:title/

collections:
  teaches:
    output: true
  is-all-about:
    output: true
  makes-things:
    output: true
